### ISSUE TITLE
Initial setup error on windows

### ISSUE THREAD

**Issue by emersonbottero** [svitejs/vite-plugin-template#23]
### Describe the bug

first install: updating template to match repo "emersonbottero/vite-plugin-search"
initial setup failed [Error: EPERM: operation not permitted, rename 'C:\Users\emers\Source\Repos\vite-plugin-search\.github\workflows.tpl' -> 'C:\Users\emers\Source\Repos\vite-plugin-search\.github\workflows'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\emers\\Source\\Repos\\vite-plugin-search\\.github\\workflows.tpl',
  dest: 'C:\\Users\\emers\\Source\\Repos\\vite-plugin-search\\.github\\workflows'
}

### Reproduction

use as template
clone repo
pnpm i
npm run setup
first install: updating template to match repo "emersonbottero/vite-plugin-search"
initial setup failed [Error: EPERM: operation not permitted, rename 'C:\Users\emers\Source\Repos\vite-plugin-search\.github\workflows.tpl' -> 'C:\Users\emers\Source\Repos\vite-plugin-search\.github\workflows'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\emers\\Source\\Repos\\vite-plugin-search\\.github\\workflows.tpl',
  dest: 'C:\\Users\\emers\\Source\\Repos\\vite-plugin-search\\.github\\workflows'
}

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 7.41 GB / 15.92 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.22621.436.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by dominikg** [comment]
I cannot reproduce this in a windows-10 vm. Renaming the directory `.github/workflows.tpl` to `.github/workflows` is done via node's own fs.rename: https://github.com/svitejs/vite-plugin-template/blob/7176aa591c2f8960c534fbc8bfaa39a98e103d67/scripts/initial-setup.cjs#L54

I'm guessing something is preventing the file system operation on your installation, either windows permissions, eg different user, or some anti-virus software or whatever.

You can try to use WSL or git-bash instead of cmd or powershell. But ultimately i recommend not using windows.
